apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: account-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production-account-service"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: account.lucurlings.nl
      http:
        paths:
          - backend:
              serviceName: account-service
              servicePort: 80
  tls:
    - hosts:
        - account.lucurlings.nl
      secretName: production-account-service-kwetter-tls